# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac159da1402cb048643bb1f1c53756b4f4cfc7a61b0c2c579a1e9ca0a1eaf118ec4b4d2d4f21314f5a05b20c70966a555f39a8b0e769840ee56e5acc6ffdd551

test:
  secret_key_base: dff68f44a252c599a32147cb996dcea04e7c5e9ae560ec46d7a7ca3683a96250f80bd4fd43db9ae1c9227e3fe563570a3e33923598174eeb29376124f90ae03b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
